"""平台适配层：Issue 读取、PR 发布、能力注册与共享模型的唯一入口。"""

from .errors import (
    ForgeError,
    ForgeRemoteError,
    ForkNotReady,
    GitPushError,
    InvalidForgeInput,
    InvalidProviderUrl,
    InvalidPublisherInput,
    ProviderError,
    ProviderNotConfiguredError,
    ProviderRemoteError,
    PublisherError,
    PublisherRemoteError,
    RegisteredForkMismatch,
    UnsupportedPublisher,
)
from .git_transport import GitRunner, HttpsGitPusher, SubprocessGitRunner
from .gitcode import GitCodeForge, GitCodeProvider, GitCodePublisher
from .github import GitHubForge, GitHubProvider, GitHubPublisher
from .models import (
    ForkResult,
    GitCommandResult,
    Issue,
    PRCommentResult,
    PRFeedbackItem,
    ProviderName,
    PublishResult,
    PullRequestDetails,
    Repository,
)
from .protocols import Forge, PublishRequest
from .registry import (
    ALL_FORGE_CAPABILITIES,
    ForgeCapability,
    ForgeNotConfigured,
    ForgeRegistration,
    ForgeRegistry,
)
from .urls import parse_issue_url, parse_pull_request_url, parse_repository_url

__all__ = [
    "ALL_FORGE_CAPABILITIES",
    "Forge",
    "ForgeCapability",
    "ForgeError",
    "ForgeNotConfigured",
    "ForgeRegistration",
    "ForgeRegistry",
    "ForgeRemoteError",
    "ForkNotReady",
    "ForkResult",
    "GitCommandResult",
    "GitCodeForge",
    "GitCodeProvider",
    "GitCodePublisher",
    "GitHubForge",
    "GitHubProvider",
    "GitHubPublisher",
    "GitPushError",
    "GitRunner",
    "HttpsGitPusher",
    "InvalidForgeInput",
    "InvalidProviderUrl",
    "InvalidPublisherInput",
    "Issue",
    "PRCommentResult",
    "PRFeedbackItem",
    "ProviderError",
    "ProviderName",
    "ProviderNotConfiguredError",
    "ProviderRemoteError",
    "PublishRequest",
    "PublishResult",
    "PublisherError",
    "PublisherRemoteError",
    "PullRequestDetails",
    "RegisteredForkMismatch",
    "Repository",
    "SubprocessGitRunner",
    "UnsupportedPublisher",
    "parse_issue_url",
    "parse_pull_request_url",
    "parse_repository_url",
]
